### ISSUE TITLE
SSH config file includes username in Host value

### ISSUE THREAD

**Issue by calejvaldez** [ojosproject/scripts#4]
The SSH setup script adds a Host with the value `git@github.com`, which causes a bug. It should instead simply be `github.com`.

**Comment by calejvaldez** [comment]
Bug located [here](https://github.com/ojosproject/scripts/blob/aee988d6e8970118f930e6f6d82e6e069f15daf9/ssh-setup/ssh-setup.sh#L28).

**Comment by AyushJain2021** [comment]
Fixed in bf449223d59c0003bd57d4564494f0fc0f216f63
